### ISSUE TITLE
Stochastic decorators: value outside support

### ISSUE THREAD

**Issue by thommevans** [pymc-devs/pymc3#110]
I'm working with pymc 2.1alpha because that's what's installed at my department, so I'm sorry if this is an issue that's been fixed up in more recent updates. But I'm having trouble defining Stochastic variables with the decorator syntax. 

In fact, the model_3.py and model_4.py modules in the pymc/examples folder which use the decorator syntax to define the variables 'params_of_mean' and 'disasters' both crash for me upon import, returning the error message:

> > form pymc.examples import model_3

ZeroProbability: Stochastic params_of_mean's value is outside its support,
 or it forbids its parents' current values.

> /usr/local/scisoft/packages/python/lib/python2.6/site-packages/pymc/PyMCObjects.py(657)get_logp()
>     656             else:
> --> 657                 raise ZeroProbability, self.errmsg
>     658 

And of course I get the same error messages when I try to define my own Stochastic variables with the equivalent syntax. I see that similar issues have been addressed previously, eg here:

http://groups.google.com/group/pymc/browse_thread/thread/aae4c718eeac33b1/11d1a6fa5c6806cf?show_docid=11d1a6fa5c6806cf

but the solution offered there still seems to fail for me with the same error as above. I should also note that I don't see any failures when I run pymc.test().

**Comment by fonnesbeck** [comment]
Hi Tom,

That's a very old version of PyMC -- I strongly recommend having it upgraded. We are days away from the official 2.2 release. That particular model, which has since been replaced in the example set, runs fine under the current codebase. If you are unable to have the department-wide site-packages directory, you can set up a local one (e.g. in your home directory) and change your PYTHONPATH variable to point to it.

cf

**Comment by thommevans** [comment]
OK, updating and overriding my department's pre-installed version was worth it - it works now with 2.1beta. Sorry about that... 

I look forward to v2.2!
