### ISSUE TITLE
PyMC with Hadoop?

### ISSUE THREAD

**Issue by laserson** [pymc-devs/pymc3#137]
Are there any plans in the works to transparently allow PyMC to work on a hadoop cluster?

**Comment by fonnesbeck** [comment]
Not sure how this would work. I know you can do MapReduce in Python pretty easily, but how does MCMC figure into these sorts of operations?

That said, there is a general goal of making PyMC parallel in the next major version.

**Comment by frgomes** [comment]
IMHO, the better way of integrating Python and Java would be using a 
messaging layer, possibly using Apache/Qpid, which is pretty simple to 
integrate an use. Using an integration layer is good because you free 
yourself of using JNI or JNA or some other similar dirty way of doing 
things.

If you believe that "less is more"... you could simply remove Hadoop 
from the equation.
Since you have map/reduce operations in Python and since you are able to 
deliver/receive messages to/from other nodes using Apache/Qpid ... why 
do you need anythong more complicated than that?

http://qpid.apache.org/books/0.16/Programming-In-Apache-Qpid/html/index.html
http://qpid.apache.org/apis/0.16/python/html/index.html

Thanks

Richard Gomes
http://launchpad.net/~frgomes
mobile  : +44(77)9955-6813
email   : rgomes1997@yahoo.co.uk

**Comment by laserson** [comment]
Well, barring fancier stuff, lots of MCMC sampling is embarrassingly parallel, so this can be an easy way to do large-scale sampling on a whole cluster in a way that's pretty much transparent to the user.  Hadoop could be used to send out MCMC tasks to a large cluster without the user having to deal with the complexities of parallelization at all.  I also imagine you could connect PyMC to an HBase backend for very large-scale sampling.  The data would be stored on a distributed file system, and the user could perform follow up analysis very naturally.

**Comment by laserson** [comment]
Richard: excuse my naivete, but how does Qpid solve this problem?  It seems that the user would still have to write some potentially complex code to manage the parallelization.  And the potentially large amount of data would need to be aggregated somewhere.  The idea is not to integrate python with java.  The idea is to use a resource scheduling scheme that's already built to easily and transparently scale PyMC up to a large cluster.  That it's implemented in java is not even relevant to the user.

**Comment by frgomes** [comment]
Hello Uri,

My turn to be naive: how do you define "user"?

To me, looks like someone skilled enough is needed in order to make 
things happen: move data back and forth Hadoop and computation nodes, in 
a nutshell. From my perspective, a developer able to do this would be 
able to use a messaging layer directly, without having to delegate tasks 
to Hadoop.

I don't have anything against Hadoop. Please don't get me wrong. Java 
pays my bills for more than 10 years.
I just don't find the economics advantageous. I explain:

On one hand, you gain all features Hadoop can offer. Do you really need 
all of that?
On the other hand, you have to deal with integration problems and 
infrastructure costs due to an architecture which, to me, looks more 
complicated than it needs to be.

A quick googling showed me: 
http://code.google.com/p/octopy/wiki/UsageExamples
No. I don't have any experience with this thing. But be sure I will give 
it a try.
The possibility of throwing away Apache Qpid from the solution is 
definitely attractive to me :)

Again... how to you define "user"?

Thanks

Richard Gomes
http://launchpad.net/~frgomes
mobile  : +44(77)9955-6813
email   : rgomes1997@yahoo.co.uk

**Comment by laserson** [comment]
I agree with you that people that could/would use Hadoop are probably able enough to write the parallelization themselves.  But I think there are a lot of people out there that are trying to change this situation and make Hadoop a lot more accessible.  Also, it seems that you connect PyMC to a number of different database backends.  It seems to me that having a connector for HBase or just plain HDFS is very natural, and should easily allow for generating very large samples.  And dispatching to hadoop seems like an easy way to help generate the large amount of samples.

I guess I agree with you that people could write the parallelization themselves.  But I've written a little bit of my own parallelization code in the past, and I find it a pain, especially in terms of dealing with failed tasks, etc.  This is exactly the part that hadoop has already solved: dispatch and manage jobs on a cluster, recover from failures, and writing large volumes of data to a file system.  PyMC could connect with some of the Hadoop wrappers already written for python, and make it very easy for someone sitting on a cluster to sample simultaneously on, say 1000 nodes.

Uri

**Comment by twiecki** [comment]
I think Hadoop is not the right way to go about this. Spark would be more appropriate but that would be a huge project outside the scope of pymc.

**Comment by laserson** [comment]
@twiecki out of curiosity, why do you think Spark is more appropriate in this case?  I think the idea would be to use HDFS as a backend to store a potentially very large number of samples.  Both Spark and Hadoop use HDFS as their datastore.  Both are written on the JVM, so python integration is generally not as smooth.  Spark does provide a python API, which might make parallelizing jobs easier, but probably not that much easier...

**Comment by jsalvatier** [comment]
Spark is more appropriate because it is dramatically faster than Hadoop.
Spark _can_ use HDFS but it normally uses the RAM on the cluster.

**Comment by twiecki** [comment]
Right. Hadoop is really bad at anything iterative (like MCMC) because it requires many map-reduce steps that have to reload the data. Spark is much smarter about caching and chaining computations.

**Comment by laserson** [comment]
So it sounds like this ultimately is a question of scale.  HDFS is obviously a good idea to persist a large number of samples that require a distributed environment.  For analytics on the generated data, if you can fit all your samples into RAM, then Spark will be far more convenient; if you cannot fit into RAM, it's a tossup.

**Comment by twiecki** [comment]
Well or you could distribute your data across more spark nodes.

**Comment by sthomas-github** [comment]
I've been wondering about this question of how PyMC could be applied in a scaled, distributed, or even soft real-time/streaming scenario ever since being exposed to it.  From what I know about Spark, I agree with Mr. Wiecki that it sounds like a good platform to address the issue.  I'd be very interested in any developments in this area.

**Comment by laserson** [comment]
@sthomas-github, an intern at Cloudera, @mertterzihan, is working on PyMC/Spark integration.  You can see the progress on the `pyspark` branch: https://github.com/mertterzihan/pymc

**Comment by sthomas-github** [comment]
@laserson, Thanks for the tip!  That's great.
