### ISSUE TITLE
Making tests easier to use

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#216]
In cad059eb220567462665c849905a7411de2c2018 on the `metropolis` branch, I tried to make tests a little easier to run  by moving them inside `pymc/` and adding a `test` function, so they can be run by:

```
import pymc
pymc.test()
```

Happy with this?

We may want to make the tests more friendly to being run as a batch, for example, by turning off the progress bar and making the MCMC runs short.

**Comment by jsalvatier** [comment]
I currently run tests by using nosetests: `nosetests -v` (I'm assuming this still works). Is the idea to eliminate the nosetests dependency? 

Reducing feedback time by reducing testing time and verbosity is a good idea I think. 

Would you submit these changes as a pull request?

**Comment by jsalvatier** [comment]
I think this change has broken the tests in Travis (see the bottom of https://s3.amazonaws.com/archive.travis-ci.org/jobs/6860183/log.txt), I think the problem comes from tests/ having been moved. You can change how nosetests gets called by changing the .travis.yml file (https://github.com/pymc-devs/pymc/blob/pymc3/.travis.yml)

**Comment by fonnesbeck** [comment]
This is fixed in f67b50fb06cf1fd48b319fad277f616adb264ef6. The tests are still pretty noisy.

**Comment by jsalvatier** [comment]
Since this is merged, I think this is addressed.
