### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#222]
PyMC 2 is licensed under the Academic Free License. Do we stick with this for v.3, or is there a compelling reason to switch (e.g. MIT, BSD)? I notice that mcex was BSD, and this code base is derived from that.

**Comment by twiecki** [comment]
Academic Free License is a little outdated I think. At least I don't know any project that still uses it. BSD is comparable but used more widely. Apache v2 is as free as BSD but more complex as it says that no one can't be sued over any software patents which is why it's preferred when a company is behind it.

**Comment by jsalvatier** [comment]
I'm in favor of whatever has the least restrictions on use. I used BSD because my understanding is it says "do whatever you want with it". It looks like Academic Free License is close to BSD, so I think either way is fine. 

@twiecki since you seem to know a little bit, what would be your recommendation?

**Comment by twiecki** [comment]
I think the question should be between BSD and Apache v2 just because they are most widely used. Between the two I have a small preference for Apache License Version 2. It is as free as BSD but the apache foundations went through great lengths to make it tight against this whole software patent madness. Essentially it says that pymc (or any 3rd party contributor) can't sue anyone who's using or changing pymc over any hidden software patent violations. This might seem like a very contrived case since I don't think @jsalvatier got granted any software patents but it gives companies that might use it (and maybe contribute back!) more guarantees.

Finally, with the recent DARPA funding initiative for probabilistic programming this might actually be more relevant.

So the worst case scenario is that all these special clauses in the apache license are never relevant. In reality, it probably doesn't matter much even if we go with BSD.

**Comment by jsalvatier** [comment]
Sounds like a good reason to go with Apache v2 as long as it's not a hassle
to make the change.

**Comment by jsalvatier** [comment]
Switching to Apache v2 seems like a good idea, but I don't think we have to worry about it right now. I don't see a reason why this has to block release.

**Comment by twiecki** [comment]
I actually already added this in a41d60a54df00ba2f439f4e3d8b6084e6c474965. Technically every file should be prefixed with a short note but this can certainly wait.
