### ISSUE TITLE
Convenience function for evaluating nodes

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#264]
We should probably provide a convenience function (primarily for debugging) that allows users to quickly evaluate the log-probability of a node for an arbitrary value passed to it.

**Comment by jsalvatier** [comment]
How does this syntax look to you?

```
y = Beta('y', 1,1)
x = Normal('x',y,1)
fn(x.logp)(x = 3, y = .5)
```

`fn` compiles a theano function which takes normal inputs (not a `Point`). This has the advantage that it generalizes to other values like `fn(x.distribution.mean)(x = 3, y =.5)`.

**Comment by twiecki** [comment]
It's a great idea.

Some minor comments:
I wonder if for some users having a function returned is a little weird. The alternative would be something like `fn(x.distribution.mean, x=3, y=.5)` which of course would lose the compiled function so not ideal either.

Also, `fn` seems rather non-descriptive but I can't currently think of an alternative. 

It's probably fine but something to think about.

**Comment by fonnesbeck** [comment]
This will be really useful. Echoing Thomas, I would imagine that the vast majority of users would want to immediately evaluate the function so we might just want to have the function return the value. My suggestion is similar:

```
calc(x.logp, x=3, y=0.5)
```

other alternatives could be `evaluate`, `call`, or similar.

**Comment by fonnesbeck** [comment]
One other idea: could PyMC objects each come with auxiliary functions that are prepended with `calc_` or similar, so that if we have a `logp` method we could also have `calc_logp` so that we could just have `calc_logp(x=3, y=0.5)`? A decorator could automate this.

**Comment by jsalvatier** [comment]
That could work. I like `calc(x.logp, x=3, y=0.5)` a bit better. 

I ran into a serious snafu with this: to support this functionality, we probably have to attach the distribution to the variable. Unfortunately the variables get serialized when using `psample` and the distributions won't serialize because they're not standard objects. Perhaps I should just suck it up and make them regular objects?

**Comment by jsalvatier** [comment]
I think I would like both a function that returns an evaluation function, currently named `fn`, and some other approach. I'm a bit partial to chris' suggestion of attaching an `eval_logp(x = 3, y =.5)` function to random variables. Thoughts on names or syntax?

**Comment by bjedwards** [comment]
Should the way this is handled in `Model` be re-evaluated? In a `Model` object, there is `logp` and `logpc`. I would be +1 to a unified design. This way evaluating log probability (or any other function) should be the same for a model as well as nodes within the model.

That said, I was a little confused at the existence of `logp` and `logpc`. For me `logp` should be the actual function and something like `_logp_fn` should be the uncompiled `TensorVariable` object. Also it might be nice to have whatever function returns the log probability take kwargs (as all have suggested) instead of a dict as `logpc` currently does. 

I understand that this might be too daunting of a refactor, but my suggestion would be to hide the uncompiled versions behind `_`, and present a unified interface for convenience functions for both the model and nodes within the model.

The downside to this is it might make writing new distributions harder, but what is the more common use case?

**Comment by twiecki** [comment]
I'm inclined to agree. Rarely users would want to access `logp` which would suggest that it shouldn't be part of the public interface.

I suppose the question is how much we really want to protect the user from the underlying Theano. So far PyMC3 is a rather thin wrapper.

**Comment by jsalvatier** [comment]
I agree that users won't want to access the theano variable logp very
often. However, I would like to expose it as an option for people, I don't
want to protect the user from the underlying Theano if they want to access
it. Perhaps we can make `.logp` a function and find some other name for the
theano variable.

**Comment by twiecki** [comment]
@jsalvatier Just to clarify, users can always access anything as there's no real private in python. But per convention, attributes or methods starting with `_` are considered not part of the interface.

**Comment by jsalvatier** [comment]
Right, I don't want to discourage people from that.

**Comment by twiecki** [comment]
OK, yeah, I can see how trying to hide the underlying Theano might be disadvantageous as so far keeping a light wrapper around theano objects has worked pretty well I think. Or what's the case you are thinking about?

**Comment by jsalvatier** [comment]
Yeah, keeping a light wrapper seems like a good idea.

**Comment by jsalvatier** [comment]
How do you guys feel about the current solution?

For Models, ObservedRV and FreeRV, `.logp(p1 = val, p2 = val2)` or `.logp(point)`  evaluates the log density at the given point. Arbitrary theano values can be computed using the function `fn`.

```
func = fn(theano_var)
func(p1 = val, p2 = val2)
```

**Comment by fonnesbeck** [comment]
Works for me:

```
In [1]: from pymc import *

In [2]: with Model() as model:
   ...:     bin = Binomial('bin', 20, 0.5)
   ...:   

In [3]: bin.logp(bin=4)
Out[3]: array(-5.3772405202909255)
```

**Comment by twiecki** [comment]
Yeah, I think this is great.

**Comment by jsalvatier** [comment]
Great!
