### ISSUE TITLE
Incompatible shapes with use of Observed=True and Size=n

### ISSUE THREAD

**Issue by JamesPHoughton** [pymc-devs/pymc3#319]
Not sure if this is a bug, or if I have a short between the chair and the keyboard, but I'm having trouble using the size parameter and the observed parameter together. Consider trying to find the weights of four biased coins:

```
numcoins=4
numtrials=50
true_p = numpy.random.random(size=numcoins)
values = numpy.random.binomial(n=1, p=true_p, size=(numtrials,numcoins))

p = pymc.Uniform('p', lower=0, upper=1, size=numcoins)
obs = pymc.Bernoulli('obs', p=p, size=numcoins, value=values, observed=True)
```

Yields error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-46dc39fa9cea> in <module>()
      1 p = pymc.Uniform('p', lower=0, upper=1, size=numcoins)
----> 2 obs = pymc.Bernoulli('obs', p=p, size=numcoins, value=values, observed=True)

/Library/Python/2.7/site-packages/pymc/distributions.pyc in __init__(self, *args, **kwds)
    242 
    243                 if init_val_shape is not None and shape is not None and init_val_shape != shape:
--> 244                     shape_error()
    245 
    246                 given_shape = init_val_shape or shape

/Library/Python/2.7/site-packages/pymc/distributions.pyc in shape_error()
    239 
    240                 def shape_error():
--> 241                     raise ValueError('Shapes are incompatible: value %s, largest parent %s, shape argument %s'%(shape, init_val_shape, parents_shape))
    242 
    243                 if init_val_shape is not None and shape is not None and init_val_shape != shape:

ValueError: Shapes are incompatible: value (4,), largest parent (50, 4), shape argument (4,)
```

**Comment by fonnesbeck** [comment]
Yes, unfortunately PyMC does not automatically cast the dimensions of the parameters up to that of the values, unless the parameter is a scalar and the value is an array. So, the parameter either has to be a scalar or be the same size as the value.

So, you have two options: you can loop over the coins (or the trials), creating a Bernoulli likelihood for each coin (trial):

```
for i in range(numcoins):
    obs_i = pymc.Bernoulli('obs_%s' % i, p=p[i], value=values[:,i], observed=True)
```

or you can vectorize things by resizing `p` in a `Lambda` object:

```
ps = pymc.Lambda('ps', lambda p=p: np.reshape(p, (numtrials,numcoins)))
obs = pymc.Bernoulli('obs', p=ps, value=values, observed=True)
```

(note that you don't have to pass a `size` parameter if you pass a value, since it can infer the size from the shape of the value)

This is due to the fact that the likelihoods are all Fortran, which makes it hard to match dimensions easily. We thought about doing fancy resizing, etc. before sending the values to Fortran, but wanted to keep things simple and not have all sorts of size-checking going on every time a likelihood is called.

When we move to PyMC 3, this should not be a problem, since we are dropping all the Fortran code.

**Comment by JamesPHoughton** [comment]
Thanks, that'll do nicely.

**Comment by jsalvatier** [comment]
Yes it is. Can you post the code you're using and the shape of the data
array?

**Comment by stefan-pdx** [comment]
Thanks for getting back. I was able to figure out how to pass in values for a multi-dimensional Stochastic variable. I ended up having to cast my data to a tuple of arrays, as shown [here](https://github.com/pymc-devs/pymc/blob/fd63b82464443cba7263230985eceec8d81b15e3/pymc/model.py#L385-L391), otherwise my values were being interpreted as `[data]`. Perhaps the documentation can be updated to explain this edge case?

Thanks!

**Comment by jsalvatier** [comment]
Yes, that's probably a good idea.

**Comment by stefan-pdx** [comment]
Hm, I've come across this problem again:

``` python
mus = np.random.poisson(5, size=(5,))
# array([6, 2, 1, 8, 1])

samples = tuple(np.random.poisson(10, size=(mu,)) for mu in mus)
# (array([ 3,  5, 10, 11, 14, 11]),
# array([14, 15]),
# array([8]),
# array([14,  7, 10, 13,  8, 13, 12, 10]),
# array([8]))

mc.Poisson('foo', mu=mus, value=samples, observed=True, size=len(samples))
```

generates the exception:

```
/usr/local/lib/python2.7/site-packages/pymc/PyMCObjects.pyc:726

ValueError: Stochastic foo: Failed to cast initial value to required dtype.

Original error message:
setting an array element with a sequence.
```

It looks like that the samples observed are trying to be converted over to an array of `dtype=int64` as the below reproduces the issue:

``` python
np.asanyarray(samples, dtype=np.int64)
```

Is it possible to provide a multivariate Poisson variable a tuple/list of arrays representing the observations in PyMC 2.3?

**Comment by stefan-pdx** [comment]
I believe I was able to come up with a workaround:

``` python
@mc.observed(dtype=np.object)
def foo(value=samples, mu=mus, size=len(samples):
     return np.vectorize(mc.poisson_like)(*numpy.vstack((value, mu))).sum()
```

**Comment by fonnesbeck** [comment]
Interesting. Can you verify that it generates the correct result?

In cases where I have arrays/lists of different lengths, I typically concatenate them together and index them. Something like:

```
In [16]: np.r_[samples]
Out[16]: 
array([ 5,  8, 11, 10, 11,  9,  9, 10,  9, 18, 10, 11, 12, 15,  9, 12,  9,
        9])

In [17]: mus[np.sum([[i]*len(s) for i,s in enumerate(samples)])]
Out[17]: [2, 2, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3]
```

and use those in the Poisson likelihood.
