### ISSUE TITLE
Proposal: move pymc3 to separate repo

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#365]
I think we should move pymc3 to it's own repo in pymc-devs/pymc3 for the following reasons:
- Easier to find for users.
- We'll never be able to merge pymc3 into master as they are completely distinct.
- Since pymc3 is a complete rewrite that breaks API compatibility not everyone will switch so pymc2 is going to be in use for quite a while I think. There are also good reasons for sticking with pymc2 as it's tried and tested and lots of models already exist for it.
- Github issues are not overlapping.

It's kinda like Python2 :: Python3 just more extreme.

**Comment by fonnesbeck** [comment]
I see the logic, but the main issue I have is that when PyMC 3 becomes the default version (several months from now?), I would like it to be `pymc-devs/pymc` and not `pymc3`. If we were to break the repo in two, I would rather have it the other way around, where we have a `pymc-devs/pymc2` repo for the current version.

I agree that we want PyMC 3 to be more readily available, but I think users that will stick with version 2 won't be pulling from GitHub very often, but rather will be using release versions. Since 2.3 is ready to go, we could create a 2.3 branch upon the release, then rename pymc3 to master. The "merge" can be as simple as deleting master and then creating a new master from pymc3. Remember, there is nothing magical about master in Git; its just a name.

What do you think, @jsalvatier ?

Regarding the issues, I have tried to tag new issues as v.2 or v.3 as they come in, which makes it easy to filter them, but I have not kept up with it.

**Comment by jsalvatier** [comment]
At first glance this seems like a pretty good idea. 

I guess the major thing is that it will be kind of confusing, when you do a google search you'll get two different versions.

**Comment by twiecki** [comment]
Those are good points. I think @fonnesbeck's approach makes a lot of sense.

**Comment by fonnesbeck** [comment]
Ok, so the plan will be (1) tag 2.3 release (2) rename master to v2.3 (3) rename pymc3 to master. 

This will startle some users, but that's life. Will test it locally and see how it goes.

**Comment by fonnesbeck** [comment]
OK, the deed is done. The `pymc3` branch is now `master` and the PyMC 2 source is now in branch `2.3`.

**Comment by jsalvatier** [comment]
Is that going to cause havoc with people's local repos when they try to
pull?

**Comment by fonnesbeck** [comment]
It might, but it will only be painful once. I have added a warning in the main page of the repo. I don't think it will be too bad.
