### ISSUE TITLE
"global name Model is not defined" error

### ISSUE THREAD

**Issue by raddy** [pymc-devs/pymc3#418]
Spent a few hours trying to debug this without much luck -- even the simplest possible models in pymc3 are giving me "global name Model is not defined" error...

Example:

```
    import numpy as np
from pymc import  *
from pymc.distributions.multivariate import Dirichlet


model = Model()
with model:
    p, p_m1 = model.TransformedVar(
                 'p', Dirichlet(2,2, shape = 2), 
                 simplextransform)


    h = hessian(model.logp)
```

**Comment by jsalvatier** [comment]
Seems like some kind of installation error. Are you sure you have the github version of pymc?

**Comment by raddy** [comment]
Aha!

The above code is incorrect -- the call to Dirichlet needs to be a call to Dirichlet.dist() instead.

I assume the error is cryptic due to Theano weirdnesses.

**Comment by jsalvatier** [comment]
No, this one is our issue. I'll have to investigate how to make the error
message more informative.

**Comment by jsalvatier** [comment]
Glad you were able to get it resolved. :)

**Comment by kyleam** [comment]
> The above code is incorrect -- the call to Dirichlet needs to be a call
> to Dirichlet.dist() instead.

Although this is true, I don't think this is related to the original
issue. When I run it with `dirichlet` instead of`dirichlet.dist`, it
fails differently (and I think appropriately):

```
Traceback (most recent call last):
  File "pymc-global-original.py", line 9, in <module>
    'p', Dirichlet(2,2, shape = 2),
  File "/home/kyle/src/python/pymc/pymc/distributions/distribution.py", line 23, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/home/kyle/src/python/pymc/pymc/distributions/distribution.py", line 29, in dist
    dist.__init__(*args, **kwargs)
  File "/home/kyle/src/python/pymc/pymc/quickclass.py", line 10, in __init__
    self.__dict__.update(f(*args, **kwargs))
  File "/home/kyle/src/python/pymc/pymc/quickclass.py", line 76, in newf
    r1 = f(*args_a, **kwargs_a)
TypeError: Dirichlet() missing 1 required positional argument: 'a'
```

I'd guess the model "global name Model is not defined" is a completely
unrelated install issue.

Did you reinstall anything along the way? Perhaps that fixed the
original issue. If this is the case, when you remove `dist` now and
rerun, you should now get something similar to the error I got above.

What version of pymc are you using?
