### ISSUE TITLE
Gibbs sampler missing

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#447]
To my understanding, Gibbs sampling updates a set of random variables conditional on the rest of the RVs (how you sample from the conditional is secondary, can be metropolis or slice...). The closest thing pymc3 is CompoundStep, however, for a single sample it updates _all_ RVs in sequence. But for Gibbs one has to only update one set of RVs to create a single sample, rather than all of them.

Here is a Gibbs sampler similar to `CompoundStep`:

``` python
from numpy.random import randint
from itertools import cycle

class Gibbs(object):
    """Step method composed of a list of several other step methods applied in sequence or randomly."""
    def __init__(self, methods):
        self.methods = list(methods)
        self.cycle_index = cycle(range(len(self.methods)))

    def step(self, point):
        index = self.cycle_index.next()
        point = self.methods[index].step(point)

        return point
```

If everyone agrees with my view I can just include that in gibbs.py but wanted to do a sanity check first.

**Comment by bjedwards** [comment]
From my understanding, a Gibbs sampler updates each variable individually, or blocks of variables, from the conditional distribution when the rest of the variables are fixed (how you describe the current `CompoundStep` method). So shouldn't compound step be for using different sampling methods on different variables and then a Gibbs sampler would be like a compound step except the sampler (HMC, Metropolis, NUTS), is used on each variable in turn.

I also could be completely wrong.

**Comment by twiecki** [comment]
> From my understanding, a Gibbs sampler updates each variable individually, or blocks of variables, from the conditional distribution when the rest of the variables are fixed (how you describe the current CompoundStep method).

Yes, same page.

> So shouldn't compound step be for using different sampling methods on different variables and then a Gibbs sampler would be like a compound step except the sampler (HMC, Metropolis, NUTS), is used on each variable in turn.

`CompoundStep` takes a list of step methods and applies them in sequence so it already works as you describe.

The main point here is that while `CompoundStep` is a Gibbs sampler, it is an inefficient one as it updates _all_ variables (i.e. calls their step method) to produce a single sample  while Gibbs sampling only requires you to update a single variable to produce a sample.

In addition, what's the difference from calling `sample(100, [step1, step2])` and `sample(100, CompoundStep([step1, step2]))`? I think @jsalvatier wrote `CompoundStep` so maybe he has input?

**Comment by bjedwards** [comment]
I see what you are saying. I guess I was viewing a Gibbs a sampling method, rather than a type of 'meta-sampler' like compound step. It might be nice to be able to use Gibbs like any other sampler. That is be able to do simply:

``` python
with model:
    step = Gibbs(method=Metropolis) # Actual pass the constructor rather than the object.
    trace = sample(100, Gibbs)
```

Then have it looks something like (totally untested)

``` python
class Gibbs(object):
    """Step method composed of a list of several other step methods applied in sequence or randomly."""
    def __init__(self, vars = None,method=Metropolis):
        model = modelcontext(model)
        if vars is None:
            vars = model.cont_vars

        self.methods = [method(vars=[v] for v in vars]]

        self.cycle_index = cycle(range(len(self.methods)))

    def step(self, point):
        index = self.cycle_index.next()
        point = self.methods[index].step(point)

        return point
```

`methods` could also accept a list if you wanted to do a different step method for individual vars, that is it either has to be a single step method or define a specific one for each variable.

**Comment by twiecki** [comment]
Yeah, I thought about that way as well. There's a trade-off between flexibility and succinctness here. My way is more flexible as you can combine step-methods freely and can do arbitrary groupings of variables. Your design forces the use of the same set-method for all individual variables.

Then there's the issue of PyMC 2 where people would write code similar to here using Metropolis and getting Metropolis-within-Gibbs, while PyMC3 just gives Metropolis. I do think PyMC3 is more correct although that distinction isn't very well known I feel.

We could also have a flexible `Gibbs` (my code above) and a `WithinGibbs` (your code).

**Comment by bjedwards** [comment]
The more I think about it, the more I think your approach is correct. An example could be included with something like this to make it clear what's happening

``` python
with model:
    # update 1 variable per step based on the conditional distribution
    steps = [Metropolis(vars=[v]) for v in model.vars]
    gibbs_sampler = Gibbs(methods=steps)
    trace_gibbs = sample(1000,step=gibbs_sampler)

    # update all variables each step based on the conditional distribution
    steps = [Metropolis(vars=[v] for v in model.vars]
    compound_sampler = CompoundStep(methods=steps)
    trace_compound = sample(1000,compound_sampler)
```

Traceplots and timings of these could be included to demonstrate the difference.

**Comment by twiecki** [comment]
Just looking into this more and discussing with @isofer it turns out I was completely wrong about everything. 

It's indeed only Gibbs sampling when you sample from the conditional which we aren't doing here. The confusion arises because of the badly named Metropolis-within-Gibbs or Slice-within-Gibbs samplers that do not sample from the conditional but instead use metropolis or slice to generate that conditional sample, respectively.

Also, indeed all variables have to be updated. So it seems that `CompoundStep` is all that's required.

Having said that, we could add convenience samplers called `SingleComponentMetropolis` and `SingleCompomnentSlice` sampling to point pymc 2 users towards.

Anyway, closing this to avoid further confusion.

**Comment by bjedwards** [comment]
Good to know. Just for my own edification, now that I've done a little bit of reading. If we wanted to do a Gibbs sampler correctly, we'd have to construct a conditional distribution p(v_k|v_1..v_(k-1), v_(k+1)...v_n) for each variable v_k. Since a recent patch allows for the evaluation of logp at nodes as well as random values, we could theoretically do this at some point in the future for arbitrary models?

**Comment by fonnesbeck** [comment]
The problem with Gibbs sampling is that, though it is efficient (it does not require an acceptance step) it requires full conditionals to be specified. This is not only difficult/impossible for many models, but also forces us to use conjugate forms that may not be justified other than as an expedient means for constructing the conditionals.

**Comment by twiecki** [comment]
I agree with @fonnesbeck. Although it might be possible to derive these automatically using `sympy`.

Having said that, it's probably not worth the bother since Gibbs is (i) rather constrained as @fonnesbeck pointed out and (ii) inferior to NUTS, especially with correlations and high dimensions.

**Comment by isofer** [comment]
I think there is still some confusion.
This is as I understand it from reading Gilks's textbook "MCMC in practice"
Metropolis-within-Gibbs is not a gibbs a sampler, but Slice-within-Gibbs is
a Gibbs sampler, since in each step it samples from the conditional
distribution. Gibbs sampler does not mean that the priors should be
conjugate. It just means that there is some way to sample from the
conditional distribution. Any collection of step methods that will allow
sampling from the conditional will work, (including rejection sampling,
adaptive rejection sampling, slice sampling, etc).

I think the confusion comes from the wikipedia article for slice sampling,
which is not that clear.
in a multivariate model, one could apply slice sampling to sample all the
variables together. This means that it won't act as a Gibbs sampler.
Of course, this is rarely done, and what people do is iterate over the
variables - sampling each one in its turn. This actually create a Gibbs
sampler using the Slice sampler as a step method.
So I believe the name Slice-within-Gibbs (which I do not remember seeing
anywhere but here) is accurate, and if I'm not mistaken this is the way
JAGS is implemented.

Nonetheless, I feel that the names SingleComponentMetropolis and
SingleCompomnentSlice
are quite good.
