### ISSUE TITLE
Using traceplot on trace returned by nbsample raises exception

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#632]
```
/home/wiecki/working/projects/pymc/pymc/plots.py in traceplot(trace, vars, figsize, lines, combined, grid)
     46 
     47     for i, v in enumerate(vars):
---> 48         for d in trace.get_values(v, combine=combined, squeeze=False):
     49             d = np.squeeze(d)
     50             d = make_2d(d)

TypeError: get_values() got an unexpected keyword argument 'combine'
```

@akloster Any idea? This does not occur if I just use `pm.sample()`.

**Comment by akloster** [comment]
The problem seems to be that iter_sample does not create a MultiTrace object. The NDArray backend does not have the combine and squeeze arguments.

The quickest fix would be to add these keyword arguments to NDArray and just ignore them, because squeeze and combine doesn't mean anything in the context of a single chain.

A better way to handle this would be to think about nbsample and iter_sample in the context of multiple chains.

**Comment by kyleam** [comment]
Can `nbsample` wrap the return value in a `MultiTrace` instance?

**Comment by akloster** [comment]
We could better change iter_sample to start with a Multitrace object. I don't have a clear picture about how single and multiple chains are supposed to work though.

**Comment by kyleam** [comment]
Currently, the intended behavior is for all user-level sampling functions to return a `MultiTrace` instance, even if they were not called in a multi-chain context (and even if the function currently doesn't support this). The motivation behind this is to expose a single trace interface.

All sampling goes through `_iter_sample`, which is tied to a single-chain context.

`iter_sample` is a wrapper around `_iter_sample` that will yield a sliced trace for the current iteration. Since the output of `iter_sample` is intended for users, it probably makes sense to change it to return a `MultiTrace` object (or at least document that it is an exception).

`sample` either calls `_sample` or its multiple processing form, `_mp_sample`, which merges the output of multiple `_sample` calls. Both `_sample` and `_mp_sample` return a `MultiTrace` instance, which `sample` passes back to the user.

To be more in line with this current setup, `nbsample` would behave more like `_sample` and use `_iter_sample` (because there doesn't seem to be any need for slicing every iteration) and then, if stopped, call `close` on the trace. Before returning to the user, it would lift the trace to a `MultiTrace` instance. Although making `iter_sample` return a `MultiTrace` would result in `nbsample` returning the right thing, using `iter_sample` instead of `_iter_sample` would lead to slicing and `MultiTrace` calls every iteration when there doesn't appear to be any need for it.

So, whether or not the user-facing sampling function is wired up for multiple chains, the current design gives responsibility to that function for going from the output of the single-chain `_iter_sample` results to a `MultiTrace` instance. Of course, whether or not we should use another design is a different issue.

**Comment by twiecki** [comment]
I agree with @kyleam that we should probably just change `iter_sample` to return a `MultiTrace`. Should be pretty straight forward, no?

**Comment by kyleam** [comment]
Should be. I'll change `iter_sample` to return a `MultiTrace`. But, as I mentioned above, while I do think `iter_sample` should return a `MultiTrace`,  I think `nbsample` might be better off using `_iter_sample`.

**Comment by kyleam** [comment]
@twiecki Please let me know if 891a26cf3 fixes the original error.

**Comment by twiecki** [comment]
@kyleam Yes, that fixes it. Feel also free to change `nbsample` to use `_iter_sample`.

**Comment by twiecki** [comment]
:+1:
